default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL') %>

development:
  <<: *default
  min_messages: debug5
  database: yard_development

test:
  <<: *default
  database: yard_test

production:
  <<: *default
